env:
  env_id: CartPoleContinuousBulletEnv-v0
  randomize: "sequential"
  seed: 0
agent:
  agent_id: ktd
  lr: 0.0022
  params: 16
  p_n: 0.60
  p_v: 0.40
  q: 0.4
  rank: 0
train:
  batch_size: 32
  n_steps: 176
  max_episodes: 5000
  max_samples: 500000
  eval_every: 500
  print_every: 100
  opt_steps: 4
