env:
  env_id: "microgrid"
  randomize: true
  seed: 0
agent:
  agent_id: ppo
  lr: 0.01
  params: 16
train:
  batch_size: 6
  n_steps: 12
  max_episodes: 1
  max_samples: 12409
  eval_every: 10
  print_every: 100
  opt_steps: 4
