env:
  env_id: vdp
  randomize: true
  seed: 0
agent:
  agent_id: ktd
  lr: 0.0048
  params: 16
  p_n: 0.86
  p_v: 0.51
  q: 0.5
  rank: 20
train:
  n_steps: 32
  batch_size: 32
  max_samples: 500000
  eval_every: 500
  print_every: 100
  opt_steps: 6
