program: main.py
method: grid
command:
  - "${env}"
  - "${interpreter}"
  - "${program}"
  - --bench_id=bullet:cartpole
  - --agent_id=ktd
  - "${args}"
metric:
  name: test/env/r
  goal: maximize
parameters:
    seed:
        values:
            - 0
            - 1
            - 2 
            - 3 
            - 4
    randomize:
        values:
            - "random"
            - "sequential"
            - "deterministic"
            - 0
early_terminate:
  type: hyperband
  s: 2
  eta: 3
  max_iter: 27

