program: main.py
method: bayes
command:
  - "${env}"
  - "${interpreter}"
  - "${program}"
  - --bench_id=bullet:cartpole
  - --agent_id=ktd
  - "${args}"
metric:
  name: test/env/r
  goal: maximize
parameters:
  rank:
    distribution: categorical
    values:
      - 0
      - 20
      - 60
  opt_steps:
    distribution: q_uniform
    min: 2
    max: 10
    q: 2
  n_steps:
    distribution: q_uniform
    min: 36
    max: 256
    q: 16
  lr:
    distribution: uniform
    min: 0.001
    max: 0.1
  q:
    distribution: q_uniform
    min: 0.1
    max: 0.5
    q: 0.1
early_terminate:
  type: hyperband
  s: 2
  eta: 3
  max_iter: 27

